version: '3.9'

networks:
  default:
    name: telegram-bot-nestjs-template-service-net
    driver: bridge

services:
  app:
    build:
      context: ./docker
      dockerfile: ./Dockerfile
    image: nestjs/base:10.4.5-alpine3.20
    restart: always
    env_file:
      - ./.env
    networks:
      - default
    ports:
      - ${APP_PORT}:3000
    volumes:
      - .:/opt
      - ./docker/storage:/home/storage:z
    working_dir: /opt
    command: npm run start:dev
    depends_on:
      - db-redis
      - db-mongo

  db-mongo:
    image: mongo:8.0.3
    restart: always
    hostname: ${MONGO_HOSTNAME}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_USERNAME: ${MONGO_INITDB_USERNAME}
      MONGO_INITDB_PASSWORD: ${MONGO_INITDB_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    networks:
      - default
    volumes:
      - ./docker/db_mongo_initdb.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  db-redis:
    image: redis:7.4.1-alpine3.20
    restart: always
    hostname: ${REDIS_HOSTNAME}
    networks:
      - default
